---
abstract: 'Dist::Zilla like GRS'
author:
  - 'celogeek <me@celogeek.com>'
build_requires:
  Carp: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-GRS
requires:
  Class::MOP: 0
  Devel::Cover: 0
  Dist::Zilla::App::Command::cover: 0
  Dist::Zilla::Plugin::AutoPrereqs: 0
  Dist::Zilla::Plugin::MetaConfig: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaResourcesFromGit: 0
  Dist::Zilla::Plugin::MinimumPerl: 0
  Dist::Zilla::Plugin::ModuleBuild: 0
  Dist::Zilla::Plugin::OurPkgVersion: 0
  Dist::Zilla::Plugin::PerlTidy: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::Prepender: 0
  Dist::Zilla::Plugin::Prereqs: 0
  Dist::Zilla::Plugin::PruneFiles: 0
  Dist::Zilla::Plugin::ReadmeMarkdownFromPod: 0
  Dist::Zilla::Plugin::ReportVersions: 0
  Dist::Zilla::Plugin::Test::Compile: 0
  Dist::Zilla::Plugin::Test::Kwalitee::Extra: 0
  Dist::Zilla::Plugin::Test::Perl::Critic: 0
  Dist::Zilla::Plugin::Test::UnusedVars: 0
  Dist::Zilla::PluginBundle::Filter: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Dist::Zilla::Role::PluginBundle::PluginRemover: 0
  IO::All: 0.45
  Moose: 0
  Pod::Coverage::TrustPod: 0
  Pod::Weaver::Config::Assembler: 0
  Test::Perl::Critic: 0
  Test::Pod::Coverage: 1.08
  namespace::autoclean: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://tasks.celogeek.com/projects/perl-modules-dist-zilla-pluginbundle-grs
  homepage: https://tasks.celogeek.com/projects/perl-modules-dist-zilla-pluginbundle-grs
  repository: https://github.com/celogeek/Dist-Zilla-PluginBundle-GRS.git
version: 0.04
x_Dist_Zilla:
  perl:
    version: 5.018001
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@GRS/@Filter/GatherDir'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@GRS/@Filter/PruneCruft'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@GRS/@Filter/ManifestSkip'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@GRS/@Filter/MetaYAML'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::License
      name: '@GRS/@Filter/License'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@GRS/@Filter/Readme'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@GRS/@Filter/ExtraTests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@GRS/@Filter/ExecDir'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@GRS/@Filter/ShareDir'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@GRS/@Filter/Manifest'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@GRS/@Filter/TestRelease'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@GRS/@Filter/ConfirmRelease'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@GRS/ModuleBuild'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: '@GRS/ReportVersions'
      version: 1.110730
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: '@GRS/OurPkgVersion'
      version: 0.004000
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@GRS/Prepender'
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@GRS/AutoPrereqs'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: '@GRS/Prereqs'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@GRS/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@GRS/Test::Compile'
      version: 2.021
    -
      class: Dist::Zilla::Plugin::Test::UnusedVars
      name: '@GRS/Test::UnusedVars'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@GRS/PodCoverageTests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@GRS/PruneFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ReadmeMarkdownFromPod
      name: '@GRS/ReadmeMarkdownFromPod'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@GRS/MetaJSON'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaResourcesFromGit
      name: '@GRS/MetaResourcesFromGit'
      version: 1.103620
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@GRS/MetaConfig'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@GRS/PodWeaver'
      version: 3.101642
    -
      class: Dist::Zilla::Plugin::PerlTidy
      name: '@GRS/PerlTidy'
      version: 0.13
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@GRS/Test::Perl::Critic'
      version: 2.112410
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee::Extra
      name: '@GRS/Test::Kwalitee::Extra'
      version: v0.2.0
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaResourcesFromGit
      name: MetaResourcesFromGit
      version: 1.103620
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300039
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300039
